# Generated by Django 4.0.1 on 2022-02-14 20:25

import algorithm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="Nom de l'algorithme")),
                ('layout', models.FileField(upload_to=algorithm.models.upload_layout)),
                ('questions', models.FileField(upload_to=algorithm.models.upload_questions)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
