# Generated by Django 4.0.1 on 2022-01-24 20:12

import catalogue.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=catalogue.models.upload_location)),
                ('no_inventaire', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('technique', models.CharField(blank=True, max_length=100, null=True)),
                ('support', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('epoque', models.CharField(blank=True, max_length=100, null=True)),
                ('type_collection', models.CharField(blank=True, max_length=100, null=True)),
                ('droits', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
